//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.19 at 11:09:15 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.simplilearn.com/lms", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.simplilearn.lms;
